spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cyci?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: khj01040322@
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: kt.soft.study.dto
  configuration:
    map-underscore-to-camel-case: true